export enum States {
	CA = 'CA',
	AZ = 'AZ',
	UT = 'UT',
	OR = 'OR',
	CO = 'CO',
	OK = 'OK',
	TX = 'TX',
	LA = 'LA',
	TN = 'TN',
	MN = 'MN',
	WI = 'WI',
	IL = 'IL',
	IN = 'IN',
	MI = 'MI',
	OH = 'OH',
	NY = 'NY',
	PA = 'PA',
	MA = 'MA',
	MD = 'MD',
	NC = 'NC',
	FL = 'FL',
	GA = 'GA',
}

const statesToCitiesMap: { [key in States]: { name: string; cities: string[] } } = {
	CA: { name: 'California', cities: ['Golden State', 'LA', 'Los Angeles', 'Sacramento'] },
	AZ: { name: 'Arizona', cities: ['Phoenix'] },
	UT: { name: 'Utah', cities: ['Utah'] },
	OR: { name: 'Oregon', cities: ['Portland'] },
	CO: { name: 'Colorado', cities: ['Denver'] },
	OK: { name: 'Oklahoma', cities: ['Oklahoma City'] },
	TX: { name: 'Texas', cities: ['Dallas', 'Houston', 'San Antonio'] },
	LA: { name: 'Louisiana', cities: ['New Orleans'] },
	TN: { name: 'Tennessee', cities: ['Memphis'] },
	MN: { name: 'Minnesota', cities: ['Minnesota'] },
	WI: { name: 'Wisconsin', cities: ['Milwaukee'] },
	IL: { name: 'Illinois', cities: ['Chicago'] },
	IN: { name: 'Indiana', cities: ['Indiana'] },
	MI: { name: 'Michigan', cities: ['Detroit'] },
	OH: { name: 'Ohio', cities: ['Cleveland'] },
	NY: { name: 'New York', cities: ['Brooklyn', 'New York', 'Toronto'] },
	PA: { name: 'Pennsylvania', cities: ['Philadelphia'] },
	MA: { name: 'Massachusetts', cities: ['Boston'] },
	MD: { name: 'Maryland', cities: ['Washington'] },
	NC: { name: 'North Carolina', cities: ['Charlotte'] },
	FL: { name: 'Florida', cities: ['Miami', 'Orlando'] },
	GA: { name: 'Georgia', cities: ['Atlanta'] },
};

export const mapStateToCities = (state: States): { name: string; cities: string[] } => statesToCitiesMap[state];
